Repository team-chaechae/chae-chae-server, pull requests merged in 2025-07, with the labels that each got.

#30 [ FEAT ] 판매 조회 및 검색 기능 구현
  build.gradle
  src/main/java/com/project/chaechaeserver/application/response/sales/ResSalesGetByIdDTO.java
  src/main/java/com/project/chaechaeserver/application/response/sales/ResSalesSearchDTO.java
  src/main/java/com/project/chaechaeserver/application/service/sales/SalesService.java
  src/main/java/com/project/chaechaeserver/domain/model/sales/SalesEntity.java
  src/main/java/com/project/chaechaeserver/domain/repository/sales/SalesRepository.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/QueryDslConfig.java
  src/main/java/com/project/chaechaeserver/infrastructure/sales/JpaSalesRepository.java
  src/main/java/com/project/chaechaeserver/infrastructure/sales/SalesQueryRepository.java
  src/main/java/com/project/chaechaeserver/infrastructure/sales/SalesRepositoryImpl.java
  src/main/java/com/project/chaechaeserver/presentation/controller/sales/SalesController.java
Labels: 🚀 Feature, 🌐 API

#37 [ REFACTOR ] 유저 서비스 레이어 추상화 및 Redis 로직 분리, 정적 팩토리 메소드 리팩토링
  src/main/java/com/project/chaechaeserver/application/response/user/ResInternalUserPostSignupDTO.java
  src/main/java/com/project/chaechaeserver/application/service/redis/RedisRefreshTokenService.java
  src/main/java/com/project/chaechaeserver/application/service/user/InternalUserService.java
  src/main/java/com/project/chaechaeserver/application/service/user/InternalUserServiceImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/SecurityConfig.java
  src/main/java/com/project/chaechaeserver/infrastructure/service/redis/RedisRefreshTokenServiceImpl.java
  src/main/java/com/project/chaechaeserver/presentation/controller/user/InternalUserController.java
  src/main/java/com/project/chaechaeserver/presentation/filter/JwtAuthenticationFilter.java
  src/main/java/com/project/chaechaeserver/presentation/filter/JwtAuthorizationFilter.java
Labels: 🔨 Refactor

#32 [ FEAT ] 발주 생성 기능 구현
  src/main/java/com/project/chaechaeserver/application/response/order/ResCreateOrderPostDTO.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderService.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderServiceImpl.java
  src/main/java/com/project/chaechaeserver/domain/model/order/OrderEntity.java
  src/main/java/com/project/chaechaeserver/domain/model/order/constraint/StatusType.java
  src/main/java/com/project/chaechaeserver/domain/repository/order/OrderRepository.java
  src/main/java/com/project/chaechaeserver/domain/service/order/OrderDomainService.java
  src/main/java/com/project/chaechaeserver/domain/service/order/OrderDomainServiceImpl.java
  src/main/java/com/project/chaechaeserver/domain/service/products/ProductDomainService.java
  src/main/java/com/project/chaechaeserver/domain/service/products/ProductDomainServiceImpl.java
  src/main/java/com/project/chaechaeserver/presentation/controller/order/OrderController.java
  src/main/java/com/project/chaechaeserver/presentation/request/order/ReqCreateOrderDTO.java
Labels: 🚀 Feature, 🌐 API

#39 [ REFACTOR ] 판매 기능 리팩토링
  src/main/java/com/project/chaechaeserver/application/response/sales/ResSalesGetByIdDTO.java
  src/main/java/com/project/chaechaeserver/application/response/sales/ResSalesSearchDTO.java
  src/main/java/com/project/chaechaeserver/application/service/sales/SalesService.java
  src/main/java/com/project/chaechaeserver/application/service/sales/SalesServiceImpl.java
  src/main/java/com/project/chaechaeserver/domain/model/sales/SalesEntity.java
  src/main/java/com/project/chaechaeserver/domain/repository/sales/SalesRepository.java
  src/main/java/com/project/chaechaeserver/infrastructure/sales/SalesRepositoryImpl.java
Labels: 🔨 Refactor

#51 [ REFACTOR ] 상품 정보 참조 방식 및 필드 리팩토링
  src/main/java/com/project/chaechaeserver/application/response/order/ResCreateOrderPostDTO.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderServiceImpl.java
  src/main/java/com/project/chaechaeserver/domain/model/order/OrderEntity.java
  src/main/java/com/project/chaechaeserver/domain/model/order/ProductInfo.java
  src/main/java/com/project/chaechaeserver/domain/model/order/constraint/StatusType.java
  src/main/java/com/project/chaechaeserver/domain/repository/order/OrderRepository.java
  src/main/java/com/project/chaechaeserver/domain/service/order/OrderDomainServiceImpl.java
  src/main/java/com/project/chaechaeserver/domain/service/products/ProductDomainService.java
  src/main/java/com/project/chaechaeserver/domain/service/products/ProductDomainServiceImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/AuditorConfig.java
Labels: 🔨 Refactor

#52 [ FEAT ] 발주 목록 검색 조회 기능 구현
  src/main/java/com/project/chaechaeserver/application/response/order/ResOrdersSearchDTO.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderService.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderServiceImpl.java
  src/main/java/com/project/chaechaeserver/domain/model/order/constraint/StatusType.java
  src/main/java/com/project/chaechaeserver/domain/repository/order/OrderRepository.java
  src/main/java/com/project/chaechaeserver/domain/service/order/OrderDomainServiceImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/orders/OrderRepositoryCustom.java
  src/main/java/com/project/chaechaeserver/infrastructure/orders/OrderRepositoryImpl.java
  src/main/java/com/project/chaechaeserver/presentation/controller/order/OrderController.java
Labels: 🚀 Feature

#60 [ DOCS ] 발주 도메인 Swagger 문서화
  src/main/java/com/project/chaechaeserver/application/response/order/ResCreateOrderPostDTO.java
  src/main/java/com/project/chaechaeserver/application/response/order/ResOrdersSearchDTO.java
  src/main/java/com/project/chaechaeserver/application/response/order/ResUpdateOrderQuantityDTO.java
  src/main/java/com/project/chaechaeserver/application/response/order/ResUpdateOrderStatusDTO.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderService.java
  src/main/java/com/project/chaechaeserver/application/service/order/OrderServiceImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/orders/docs/OrdersControllerSwagger.java
  src/main/java/com/project/chaechaeserver/presentation/controller/order/OrderController.java
  src/main/java/com/project/chaechaeserver/presentation/request/order/ReqCreateOrderDTO.java
  src/main/java/com/project/chaechaeserver/presentation/request/order/ReqUpdateQuantityOrderDTO.java
  src/main/java/com/project/chaechaeserver/presentation/request/order/ReqUpdateStatusOrderDTO.java
Labels: 📃 Docs, 🌐 API
