Repository team-chaechae/chae-chae-server, pull requests merged in 2025-06, with the labels that each got.

#5 [ FEAT ] 회원가입 기능 구현
  build.gradle
  src/main/java/com/project/chaechaeserver/application/global/dto/ResDTO.java
  src/main/java/com/project/chaechaeserver/application/response/user/ResInternalUserPostSignupDTO.java
  src/main/java/com/project/chaechaeserver/application/service/user/InternalUserService.java
  src/main/java/com/project/chaechaeserver/domain/repository/user/InternalUserRepository.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/SecurityConfig.java
  src/main/java/com/project/chaechaeserver/infrastructure/user/InternalUserRepositoryImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/user/JpaInternalUserRepository.java
  src/main/java/com/project/chaechaeserver/presentation/controller/user/InternalUserController.java
Labels: 🚀 Feature, 🌐 API

#4 [ FEAT ] 사내 직원 등록 기능을 위한 기본 구조 설계
  build.gradle
  src/main/java/com/project/chaechaeserver/ChaeChaeServerApplication.java
  src/main/java/com/project/chaechaeserver/application/global/dto/ResDTO.java
  src/main/java/com/project/chaechaeserver/application/response/user/ResInternalUserPostSignupDTO.java
  src/main/java/com/project/chaechaeserver/application/service/user/InternalUserService.java
  src/main/java/com/project/chaechaeserver/domain/model/user/InternalUserEntity.java
  src/main/java/com/project/chaechaeserver/domain/model/user/constraint/PositionType.java
  src/main/java/com/project/chaechaeserver/domain/model/user/constraint/RoleType.java
  src/main/java/com/project/chaechaeserver/domain/repository/user/InternalUserRepository.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/SecurityConfig.java
  src/main/java/com/project/chaechaeserver/infrastructure/user/InternalUserRepositoryImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/user/JpaInternalUserRepository.java
  src/main/java/com/project/chaechaeserver/presentation/controller/user/InternalUserController.java
  src/main/java/com/project/chaechaeserver/presentation/request/user/ReqInternalUserPostSignupDTO.java
Labels: 🚀 Feature, 🙋‍♂️ Question

#10 [ FEAT ] JWT 기반 로그인 기능 구현
  build.gradle
  src/main/java/com/project/chaechaeserver/application/service/user/RedisRefreshTokenService.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/SecurityConfig.java
  src/main/java/com/project/chaechaeserver/infrastructure/security/CustomUserDetails.java
  src/main/java/com/project/chaechaeserver/infrastructure/security/CustomUserDetailsService.java
  src/main/java/com/project/chaechaeserver/infrastructure/service/redis/RedisRefreshTokenServiceImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/util/JwtUtil.java
  src/main/java/com/project/chaechaeserver/presentation/filter/JwtAuthenticationFilter.java
  src/main/java/com/project/chaechaeserver/presentation/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/chaechaeserver/presentation/request/user/ReqAuthPostLoginDTO.java
  src/main/resources/application-dev.yml
Labels: 🚀 Feature, 🌐 API

#9 [ FEAT ] 회원가입 관리자 권한 제어
  build.gradle
  src/main/java/com/project/chaechaeserver/application/service/user/RedisRefreshTokenService.java
  src/main/java/com/project/chaechaeserver/domain/model/user/constraint/PositionType.java
  src/main/java/com/project/chaechaeserver/domain/model/user/constraint/RoleType.java
  src/main/java/com/project/chaechaeserver/infrastructure/config/SecurityConfig.java
  src/main/java/com/project/chaechaeserver/infrastructure/security/CustomUserDetails.java
  src/main/java/com/project/chaechaeserver/infrastructure/security/CustomUserDetailsService.java
  src/main/java/com/project/chaechaeserver/infrastructure/service/redis/RedisRefreshTokenServiceImpl.java
  src/main/java/com/project/chaechaeserver/infrastructure/util/JwtUtil.java
  src/main/java/com/project/chaechaeserver/presentation/controller/user/InternalUserController.java
  src/main/java/com/project/chaechaeserver/presentation/filter/JwtAuthenticationFilter.java
  src/main/java/com/project/chaechaeserver/presentation/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/chaechaeserver/presentation/request/user/ReqAuthPostLoginDTO.java
  src/main/resources/application-dev.yml
Labels: 🚀 Feature, 🔨 Refactor

#15 [ FEAT ] 도커 컴포즈 파일 작성
  .gitignore
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: ⚙ Setting, 🚀 Feature, 🛰️ Deploy
